name: Continuous Integration and Deployment
on:
  push:
    branches:
      - main

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest // Usar un contenedor de Ubuntu para ejecutar el flujo de trabajo

    if: github.ref == 'refs/heads/main' // Solo ejecutar en la rama principal
    steps:
      - name: Installe Node.js 20.x // Instalar Node.js
        uses: actions/setup-node@v3 // Usar la acción de configuración de Node.js
        with:
          node-version: 20.x // Especificar la versión de Node.js

      - name: Instalar dependencias // Instalar dependencias del proyecto
        run: npm install // Ejecutar el comando de instalación de npm

      - name: Build // Construir el proyecto
        run: npm run build // Ejecutar el comando de construcción de npm

  Deploy:
    needs: Build // Este trabajo depende del trabajo de construcción
    runs-on: ubuntu-latest // Usar un contenedor de Ubuntu para ejecutar el flujo de trabajo
    if: github.ref == 'refs/heads/main' // Solo ejecutar en la rama principal
    steps:
      - uses: actions/checkout@v3 // Usar la acción de verificación para obtener el código fuente
      - name: Instalar Node.js 20.x // Instalar Node.js
        uses: actions/setup-node@v3 // Usar la acción de configuración de Node.js
        with:
          node-version: 20.x // Especificar la versión de Node.js
      - name: Install vercel CLI // Instalar la CLI de Vercel
        run: npm global add vercel // Ejecutar el comando de instalación global de npm para Vercel
      - name: Pull Vercel Environment Variables // Obtener las variables de entorno de Vercel
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }} // Ejecutar el comando de extracción de Vercel con el token de acceso
      - name: Deploy to Vercel // Desplegar en Vercel
        run: vercel deploy --no-wait --token=${{ secrets.VERCEL_TOKEN }}  // Ejecutar el comando de despliegue de Vercel con los tokens y IDs necesarios